services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - ./server:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/audio_analyzer_development
    depends_on:
      - db

volumes:
  postgres_data:
