# PostgreSQL. Versions 9.5 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: 5432
  username: <%= ENV.fetch("DATABASE_USERNAME") { "sound_scan" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { ENV["SOUND_SCAN_DATABASE_PASSWORD"] } %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sound_scan_development

test:
  <<: *default
  database: sound_scan_test

production:
  primary:
    <<: *default
    database: sound_scan_production
  cache:
    <<: *default
    database: sound_scan_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: sound_scan_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: sound_scan_production_cable
    migrations_paths: db/cable_migrate

